### ISSUE TITLE
Please remove Django<1.11 requirement

### ISSUE THREAD

**Issue by vdboor** [myarik/django-rest-elasticsearch#10]
Hi,

I'd love to use this app in a customer project, but this is sadly not possible due to `setup.py` warning to downgrade Django to 1.10.x. Is there a specific reason this requirement is there?

If not, could you please remove this requirement and release a new version?

Best,
Diederik

**Comment by myarik** [comment]
Hi,

This requirement was removed. 
Closed via e79b774a44770e9cf88a3540a41ed9b06b5ae37e

Thanks
