### ISSUE TITLE
How  to create an object in ElasticSearch 

### ISSUE THREAD

**Issue by yogeek** [myarik/django-rest-elasticsearch#18]
I have some troubles understanding how to use correctly your project :

- In the documenation, it is mentionned that we must create the mappings in Elasticsearch with "BlogIndex.init()" but in the example project, why "BlogIndex.init(using=es_client)" is commented in search_indexes.py ? Where do we have to put this line please ?

- How is it possible to create an item ? Is it possible to have an example showing how to create an object in ElasticSearch ? 

Environment : elasticsearch 5.3.2, django-rest-elasticsearch 0.3.3

Thank you

**Comment by sillyfatcat** [comment]
You can run `BlogIndex.init()` in the admin shell just once. This creates the elastic search mapping.

Creating an item strictly following the documentation, you have to create a model object. After that's been created, use the ElasticSearch serializer.

```
instance = Blog.objects.create(**kwargs)
obj = ElasticBlogSerializer(instance)
obj.save(using=es_client)
```

This is why it's useful to have this in the model's post save signal. That being said if you integrate this after your database's been populated, you would have to manually reserialize the existing entries.

**Comment by yogeek** [comment]
For the `BlogIndex.init()`, my case is an automated Django launch : no access to admin shell, I just start a docker-compose stack with Django, Postgres and ElasticSearch and all the stack must be configured directly. In this case, would you recommend to add this line at the end of each `model.py` file in order to create the mapping for each model ? 

Thank you very much for your help !

**Comment by sillyfatcat** [comment]
I suppose it doesn't hurt if you do it that way. Though I'm not sure how it behaves when you modify the ES serializer and reinitialize them. I'll have to test that.

**Comment by yogeek** [comment]
Sorry for the delay. Indeed, it works ok when initializing the mapping in the admin shell but doin git in the model class results in an error ("`Can't reproduce object`")
In the end, I had the `BlogIndex.init()` in the wsgi.py to be sure to launch it at the beginning of the application and it is ok.
Thank you for the help

**Comment by sillyfatcat** [comment]
No problem. Thankfully it worked out :)
