### ISSUE TITLE
Using serializer's to_representation

### ISSUE THREAD

**Issue by MJafarMashhadi** [myarik/django-rest-elasticsearch#3]
Why didn't you use the serializers `to_representation` method to create the list of results?

https://github.com/myarik/django-rest-elasticsearch/blob/master/rest_framework_elasticsearch/es_mixins.py#L77

It's necessary especially for the read only fields like `url` that are not stored in elastic search but are computable from the object instance.

**Comment by myarik** [comment]
If you need to get information from a database, you should use the ListAPIView instead the ListElasticAPIView. ListElasticAPIView returns directly information from the ElasticSearch, it doesn't create any requests to a database. 
The [page](https://github.com/myarik/django-rest-elasticsearch/blob/master/rest_framework_elasticsearch/es_mixins.py#L74) value in line 74 is a Search object (library `elasticsearch-dsl`) not a QuerySet object.

**Comment by MJafarMashhadi** [comment]
So there is no way to customize representation of search results in the current state?

**Comment by myarik** [comment]
1. You can add an url field to ElasticSearch index.  [documentation](http://django-rest-elasticsearch.readthedocs.io/en/latest/basic-usage.html#create-the-mappings-in-elasticsearch) 
2. You can overwrite a `list` method.

**Comment by ArtemBernatskyy** [comment]
Why not to use this approach in `ListElasticAPIView` instead [of current version](https://github.com/myarik/django-rest-elasticsearch/blob/4f2309237a024d551c57e0238d1ee0620a7de6c1/rest_framework_elasticsearch/es_mixins.py#L35)

        def list(self, request, *args, **kwargs):
            search = self.do_search()

            page = self.paginate_search(search)
            if page is not None:
                serializer = self.get_serializer(page, many=True)
                return self.get_paginated_response(serializer.data)

            serializer = self.get_serializer(page, many=True)
            return Response(serializer.data)

And to create default serializer.
Default serializer will return the [same result at it works now ](https://github.com/myarik/django-rest-elasticsearch/blob/4f2309237a024d551c57e0238d1ee0620a7de6c1/rest_framework_elasticsearch/es_mixins.py#L42).
This will allow user to specify it's own serializer for the list view.

What do you think ?
